///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class GameModel {
/*
{
  "id": "639db2e13bd8a0151636843a",
  "name": "Kingdom Hearts III",
  "year": 0,
  "cover": null,
  "summary": null,
  "categories": [
    "fear"
  ],
  "studio": null,
  "platforms": [
    "PC"
  ],
  "vote": 0,
  "voteCount": 0,
  "releaseDate": 0
}
*/

  String? id;
  String? name;
  int? year;
  String? cover;
  String? summary;
  List<String?>? categories;
  String? studio;
  List<String?>? platforms;
  int? vote;
  int? voteCount;
  int? releaseDate;

  GameModel({
    this.id,
    this.name,
    this.year,
    this.cover,
    this.summary,
    this.categories,
    this.studio,
    this.platforms,
    this.vote,
    this.voteCount,
    this.releaseDate,
  });
  GameModel.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    name = json['name']?.toString();
    year = json['year']?.toInt();
    cover = json['cover']?.toString();
    summary = json['summary']?.toString();
    if (json['categories'] != null) {
      final v = json['categories'];
      final arr0 = <String>[];
      v.forEach((v) {
        arr0.add(v.toString());
      });
      categories = arr0;
    }
    studio = json['studio']?.toString();
    if (json['platforms'] != null) {
      final v = json['platforms'];
      final arr0 = <String>[];
      v.forEach((v) {
        arr0.add(v.toString());
      });
      platforms = arr0;
    }
    vote = json['vote']?.toInt();
    voteCount = json['voteCount']?.toInt();
    releaseDate = json['releaseDate']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    data['year'] = year;
    data['cover'] = cover;
    data['summary'] = summary;
    if (categories != null) {
      final v = categories;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v);
      });
      data['categories'] = arr0;
    }
    data['studio'] = studio;
    if (platforms != null) {
      final v = platforms;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v);
      });
      data['platforms'] = arr0;
    }
    data['vote'] = vote;
    data['voteCount'] = voteCount;
    data['releaseDate'] = releaseDate;
    return data;
  }
}
