///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ErrorModel {
/*
{
  "timestamp": "2022-12-16T19:30:13.331+00:00",
  "status": 401,
  "exception": "InvalidEmailPasswordException",
  "message": "Invalid Username/Password"
}
*/

  String? timestamp;
  int? status;
  String? exception;
  String? message;

  ErrorModel({
    this.timestamp,
    this.status,
    this.exception,
    this.message,
  });
  ErrorModel.fromJson(Map<String, dynamic> json) {
    timestamp = json['timestamp']?.toString();
    status = json['status']?.toInt();
    exception = json['exception']?.toString();
    message = json['message']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['timestamp'] = timestamp;
    data['status'] = status;
    data['exception'] = exception;
    data['message'] = message;
    return data;
  }
}
