///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class LoginModelUser {
/*
{
  "id": "639f2fe4d8187558f019c137",
  "username": null,
  "bio": null,
  "email": "dogat@gameinn.com",
  "toPlayList": null,
  "followedFriends": null,
  "favoriteGames": null,
  "logs": null,
  "profileImage": null
}
*/

  String? id;
  String? username;
  String? bio;
  String? email;
  String? toPlayList;
  String? followedFriends;
  String? favoriteGames;
  String? logs;
  String? profileImage;

  LoginModelUser({
    this.id,
    this.username,
    this.bio,
    this.email,
    this.toPlayList,
    this.followedFriends,
    this.favoriteGames,
    this.logs,
    this.profileImage,
  });
  LoginModelUser.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    username = json['username']?.toString();
    bio = json['bio']?.toString();
    email = json['email']?.toString();
    toPlayList = json['toPlayList']?.toString();
    followedFriends = json['followedFriends']?.toString();
    favoriteGames = json['favoriteGames']?.toString();
    logs = json['logs']?.toString();
    profileImage = json['profileImage']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['username'] = username;
    data['bio'] = bio;
    data['email'] = email;
    data['toPlayList'] = toPlayList;
    data['followedFriends'] = followedFriends;
    data['favoriteGames'] = favoriteGames;
    data['logs'] = logs;
    data['profileImage'] = profileImage;
    return data;
  }
}

class LoginModel {
/*
{
  "user": {
    "id": "639f2fe4d8187558f019c137",
    "username": null,
    "bio": null,
    "email": "dogat@gameinn.com",
    "toPlayList": null,
    "followedFriends": null,
    "favoriteGames": null,
    "logs": null,
    "profileImage": null
  },
  "jwtToken": "eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJkb2dhdEBnYW1laW5uLmNvbSIsImlhdCI6MTY3MTQzNDQ0OSwiZXhwIjoxNjcxNTIwODQ5fQ.AfKh6kvJM1xrxUvq1NQofQCJr3C2cTn_BFE6_z3rPtE"
}
*/

  LoginModelUser? user;
  String? jwtToken;

  LoginModel({
    this.user,
    this.jwtToken,
  });
  LoginModel.fromJson(Map<String, dynamic> json) {
    user = (json['user'] != null) ? LoginModelUser.fromJson(json['user']) : null;
    jwtToken = json['jwtToken']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (user != null) {
      data['user'] = user!.toJson();
    }
    data['jwtToken'] = jwtToken;
    return data;
  }
}
