///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///

import 'dart:developer';

import './user_model.dart';

class LoginModel {
/*
{
  "user": {
    "id": "639f2fe4d8187558f019c137",
    "username": null,
    "bio": null,
    "email": "dogat@gameinn.com",
    "toPlayList": null,
    "followedFriends": null,
    "favoriteGames": null,
    "logs": null,
    "profileImage": null
  },
  "jwtToken": "eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJkb2dhdEBnYW1laW5uLmNvbSIsImlhdCI6MTY3MTQzNDQ0OSwiZXhwIjoxNjcxNTIwODQ5fQ.AfKh6kvJM1xrxUvq1NQofQCJr3C2cTn_BFE6_z3rPtE"
}
*/

  UserModel? user;
  String? jwtToken;

  LoginModel({
    this.user,
    this.jwtToken,
  });
  LoginModel.fromJson(Map<String, dynamic> json) {
    user = (json['user'] != null) ? UserModel.fromJson(json['user']) : null;
    jwtToken = json['jwtToken']?.toString();
    log(jwtToken!);
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (user != null) {
      data['user'] = user!.toJson();
    }
    data['jwtToken'] = jwtToken;
    return data;
  }
}
