///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class LoginModel {
/*
{
  "jwtToken": "eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJkb2dhdEBnYW1laW5uLmNvbSIsImlhdCI6MTY3MTIxNTU3MCwiZXhwIjoxNjcxMjE2NzcwfQ.P20UqegQCxxL7T2uOesnf0bvXuzYusOiEdIqpoFkVwQ"
}
*/

  String? jwtToken;

  LoginModel({
    this.jwtToken,
  });
  LoginModel.fromJson(Map<String, dynamic> json) {
    jwtToken = json['jwtToken']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['jwtToken'] = jwtToken;
    return data;
  }
}
