import 'package:gameinn/model/user_model.dart';

///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///

class ReviewLogModel {
/*
{
  "id": "63aacd95cbc72c30f62c1aa2",
  "user": {
    "id": "63a80f5ac5ae0f7d5c83872a",
    "username": "ayse124",
    "profileImage": null,
    "following": null,
    "logs": null
  },
  "context": "duejqksj",
  "vote": 3,
  "voted": false,
  "likeCount": 0,
  "createdAt": 1672138133,
  "updatedAt": 0
} 
*/

  String? id;
  UserModel? user;
  String? context;
  int? vote;
  bool? voted;
  int? likeCount;
  int? createdAt;
  int? updatedAt;

  ReviewLogModel({
    this.id,
    this.user,
    this.context,
    this.vote,
    this.voted,
    this.likeCount,
    this.createdAt,
    this.updatedAt,
  });
  ReviewLogModel.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    user = (json['user'] != null) ? UserModel.fromJson(json['user']) : null;
    context = json['context']?.toString();
    vote = json['vote']?.toInt();
    voted = json['voted'];
    likeCount = json['likeCount']?.toInt();
    createdAt = json['createdAt']?.toInt();
    updatedAt = json['updatedAt']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    if (user != null) {
      data['user'] = user!.toJson();
    }
    data['context'] = context;
    data['vote'] = vote;
    data['voted'] = voted;
    data['likeCount'] = likeCount;
    data['createdAt'] = createdAt;
    data['updatedAt'] = updatedAt;
    return data;
  }
}
