///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class SignUpModel {
/*
{
  "email": "oben@gameinn.com",
  "msg": "You have successfully registered with that email: oben@gameinn.com"
}
*/

  String? email;
  String? msg;

  SignUpModel({
    this.email,
    this.msg,
  });
  SignUpModel.fromJson(Map<String, dynamic> json) {
    email = json['email']?.toString();
    msg = json['msg']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['email'] = email;
    data['msg'] = msg;
    return data;
  }
}
